name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Add excecute permission
      run: |
        chmod +x ./bin/console
    - name: Build and test with RSpec
      run: |
        gem install bundler -v 2.0.2
        bundle install --retry 3
        rubocop
        bundle exec rspec spec
